apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    project: asynch
    app: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    project: asynch
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      project: asynch
      app: manager
  template:
    metadata:
      labels:
        project: asynch
        app: manager
    spec:
      imagePullSecrets:
        - name: docker-key
      securityContext:
        {}
      containers:
        - name: service
          securityContext:
            {}
          image: apiplatformreg.azurecr.io/asynch/manager:latest
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
