apiVersion: v1
kind: Service
metadata:
  name: publisher
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    project: asynch
    app: publisher
---
# Source: service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    project: asynch
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      project: asynch
      app: publisher
  template:
    metadata:
      labels:
        project: asynch
        app: publisher
    spec:
      imagePullSecrets:
        - name: docker-key
      securityContext:
        {}
      containers:
        - name: service
          securityContext:
            {}
          image: apiplatformreg.azurecr.io/asynch/publisher:latest
          imagePullPolicy: Always 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
